# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpage',
            name='format',
            field=models.CharField(choices=[(b'organization', 'Organization')], default=(b'organization', 'Organization'), max_length=32, verbose_name='page_format'),
        ),
    ]
