# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpage',
            name='publication_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='The publication date of the article', null=True, verbose_name='publication_date'),
        ),
    ]
