# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationpage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpage',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizationpage',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizationpage',
            name='description_nl',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Description'),
        ),
    ]
