# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20160529_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpage',
            options={'verbose_name': 'Practitioner', 'verbose_name_plural': 'Practitioners'},
        ),
        migrations.RemoveField(
            model_name='organizationpage',
            name='location',
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='country',
            field=models.CharField(blank=True, max_length=64, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='organizationpage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Postal code'),
        ),
    ]
