# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20160608_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationindexpage',
            options={},
        ),
    ]
