# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_type_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Type of event'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='event_type_nl',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Type of event'),
        ),
    ]
