# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindexpage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='flyer_link',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='poster_link',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_city',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_country',
            field=models.CharField(blank=True, max_length=64, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.wagtailcore.fields.StreamField([('introduction', wagtail.wagtailcore.blocks.RichTextBlock(icon='italic')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock([(b'pull_quote', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('chapter', wagtail.wagtailcore.blocks.StructBlock([(b'chapter_name', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('section', wagtail.wagtailcore.blocks.StructBlock([(b'section_name', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('subsection', wagtail.wagtailcore.blocks.StructBlock([(b'subsection_name', wagtail.wagtailcore.blocks.CharBlock(required=True))]))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_en',
            field=wagtail.wagtailcore.fields.StreamField([('introduction', wagtail.wagtailcore.blocks.RichTextBlock(icon='italic')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock([(b'pull_quote', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('chapter', wagtail.wagtailcore.blocks.StructBlock([(b'chapter_name', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('section', wagtail.wagtailcore.blocks.StructBlock([(b'section_name', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('subsection', wagtail.wagtailcore.blocks.StructBlock([(b'subsection_name', wagtail.wagtailcore.blocks.CharBlock(required=True))]))], null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_nl',
            field=wagtail.wagtailcore.fields.StreamField([('introduction', wagtail.wagtailcore.blocks.RichTextBlock(icon='italic')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock([(b'pull_quote', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('chapter', wagtail.wagtailcore.blocks.StructBlock([(b'chapter_name', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('section', wagtail.wagtailcore.blocks.StructBlock([(b'section_name', wagtail.wagtailcore.blocks.CharBlock(required=True))])), ('subsection', wagtail.wagtailcore.blocks.StructBlock([(b'subsection_name', wagtail.wagtailcore.blocks.CharBlock(required=True))]))], null=True),
        ),
        migrations.DeleteModel(
            name='EventIndexPage',
        ),
    ]
