# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('events', '0002_eventpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EventIndexPage',
        ),
    ]
