# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('events', '0003_auto_20160512_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='flyer_link',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='poster_link',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='country',
            field=models.CharField(blank=True, max_length=64, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='flyer_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='flyer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='poster_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
