# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160530_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='flyer_document',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='flyer_image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='poster_document',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='poster_image',
        ),
    ]
