# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160620_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='format',
            field=models.CharField(choices=[(b'event', 'Event')], default=(b'event', 'Event'), max_length=32, verbose_name='page_format'),
        ),
    ]
