# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160530_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='venue_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Venue'),
        ),
    ]
