# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventpage_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='address',
            new_name='venue_address',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='city',
            new_name='venue_city',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='country',
            new_name='venue_country',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='postal_code',
            new_name='venue_postal_code',
        ),
    ]
