# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160621_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='format',
            field=models.CharField(choices=[(b'event', 'Activity')], default='event', max_length=32, verbose_name='page_format'),
        ),
    ]
