# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20160530_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
