# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20160620_1259'),
        ('howtos', '0001_initial'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('articles', '0002_auto_20160620_1259'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='howtopageorganizationpage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_to_page', to='organizations.OrganizationPage'),
        ),
        migrations.AddField(
            model_name='howtopagenewsarticlepage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_to_page', to='articles.NewsArticlePage'),
        ),
        migrations.AddField(
            model_name='howtopagenewsarticlepage',
            name='how_to_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_article_pages', to='howtos.HowToPage'),
        ),
        migrations.AddField(
            model_name='howtopageeventpage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_to_page', to='events.EventPage'),
        ),
        migrations.AddField(
            model_name='howtopageeventpage',
            name='how_to_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pages', to='howtos.HowToPage'),
        ),
        migrations.AddField(
            model_name='howtopage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Featured image'),
        ),
    ]
