# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 13:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('howtos', '0002_auto_20160621_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtopage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='howtopage',
            name='description_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='howtopage',
            name='description_nl',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
