# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20160530_1220'),
        ('howtos', '0003_howtopage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToPageNewsArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_to_page', to='articles.NewsArticlePage')),
                ('how_to_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_article_pages', to='howtos.HowToPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
