# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160908_2125'),
        ('howtos', '0004_auto_20160908_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToIndexPageStaticContentPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('howto_index_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_content_placements', to='howtos.HowToIndexPage')),
                ('static_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.StaticContent')),
            ],
            options={
                'verbose_name': 'Static content placement',
                'verbose_name_plural': 'Static content placements',
            },
        ),
    ]
