# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160615_1154'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageStaticContentPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_content_placements', to='home.HomePage')),
                ('static_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.StaticContent')),
            ],
            options={
                'verbose_name': 'Static content placement',
                'verbose_name_plural': 'Static content placements',
            },
        ),
    ]
