# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('articles', '0003_auto_20160512_1051'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticlePageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='articles.NewsArticlePage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_newsarticlepagetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reportarticlepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='reportarticlepagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ReportArticlePageTag',
        ),
    ]
