# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0003_auto_20160621_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionpage',
            name='format',
            field=models.CharField(choices=[(b'theory', 'Theory')], default=b'theory', max_length=32, verbose_name='page_format'),
        ),
    ]
