# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160615_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='body_en',
            field=models.TextField(help_text='Static HTML content for placement in pages', null=True, verbose_name='HTML Body'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='body_nl',
            field=models.TextField(help_text='Static HTML content for placement in pages', null=True, verbose_name='HTML Body'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='title_en',
            field=models.CharField(help_text='Static HTML content for placement in pages', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='title_nl',
            field=models.CharField(help_text='Static HTML content for placement in pages', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
