# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160615_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='slug',
            field=models.SlugField(default='asdf', help_text='Slug of HTML content', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='title',
            field=models.CharField(help_text='Title of HTML content', max_length=255, verbose_name='Title'),
        ),
    ]
