# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('events', '0003_auto_20160512_1051'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('articles', '0003_auto_20160512_1051'),
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0028_merge'),
        ('tags', '0002_auto_20160512_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportArticlePage',
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.AuthorPage', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='event_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_article_page', to='events.EventPage'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='featured_image'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.NewsArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
