# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160512_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([(b'featured_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'featured_embed', wagtail.wagtailembeds.blocks.EmbedBlock())], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storyarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([(b'featured_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'featured_embed', wagtail.wagtailembeds.blocks.EmbedBlock())], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([(b'featured_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'featured_embed', wagtail.wagtailembeds.blocks.EmbedBlock())], default=''),
            preserve_default=False,
        ),
    ]
