# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 12:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160512_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([('featured_image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', label='Image', template='articles/blocks/featured_video.html')), ('featured_embed', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media', label='Embedded video or audio', template='articles/blocks/featured_video.html'))]),
        ),
        migrations.AlterField(
            model_name='storyarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([('featured_image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', label='Image', template='articles/blocks/featured_video.html')), ('featured_embed', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media', label='Embedded video or audio', template='articles/blocks/featured_video.html'))]),
        ),
        migrations.AlterField(
            model_name='theoryarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([('featured_image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', label='Image', template='articles/blocks/featured_video.html')), ('featured_embed', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media', label='Embedded video or audio', template='articles/blocks/featured_video.html'))]),
        ),
    ]
