# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20160621_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theoryarticlepage',
            name='format',
            field=models.CharField(choices=[(b'theory', 'Theory Article'), (b'audio', 'Audio embed'), (b'video', 'Video embed')], default='theory', max_length=32, verbose_name='page_format'),
        ),
    ]
