# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160621_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='format',
            field=models.CharField(choices=[(b'event', 'Activity'), (b'images', 'Slideshow'), (b'audio', 'Audio'), (b'video', 'Video')], default='event', max_length=32, verbose_name='page_format'),
        ),
        migrations.AlterField(
            model_name='storyarticlepage',
            name='format',
            field=models.CharField(choices=[(b'text', 'Story'), (b'audio', 'Audio'), (b'video', 'Video'), (b'images', 'Slideshow')], default='text', max_length=32, verbose_name='page_format'),
        ),
        migrations.AlterField(
            model_name='theoryarticlepage',
            name='format',
            field=models.CharField(choices=[(b'theory', 'Theory'), (b'audio', 'Audio'), (b'video', 'Video')], default='theory', max_length=32, verbose_name='page_format'),
        ),
    ]
