# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160512_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([('featured_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))])), ('featured_video', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))])), ('featured_audio', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))]))]),
        ),
        migrations.AlterField(
            model_name='storyarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([('featured_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))])), ('featured_video', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))])), ('featured_audio', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))]))]),
        ),
        migrations.AlterField(
            model_name='theoryarticlepage',
            name='featured',
            field=wagtail.wagtailcore.fields.StreamField([('featured_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))])), ('featured_video', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))])), ('featured_audio', wagtail.wagtailcore.blocks.StructBlock([(b'embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))]))]),
        ),
    ]
