# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20160512_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='storyarticlepage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='theoryarticlepage',
            name='featured_image',
        ),
    ]
