# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
